name: Download File from S3
on:
  workflow_dispatch:

jobs:
  download_file:
    runs-on: ubuntu-latest

    outputs:
      # Define the output variable new_version
      id: download_file_output
      value: ${{ steps.download_file.outputs.new_version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download file from S3
      run: |
        aws s3 cp s3://ver-bucket-test/version.txt .
        current_version=$(cat version.txt)
        new_version=$(echo $current_version | awk -F'.' '{print $1"."$2"."$3+1}')
        echo "file version = $new_version" > test.txt
        echo "::set-output name=new_version::$new_version"

    - name: Show updated version
      run: cat version.txt

    - name: Update version in app.ts
      run: |
         python update_version.py "${{ needs.download_file.outputs.new_version }}"
        
    - name: Commit and Push Changes
      run: |
        git config --local user.email "sijinthomaspalliyady@gmail.com"
        git config --local user.name "Sijin Thomas"
        git add test.txt app.ts
        git commit -m "Increment version to ${{ steps.increment_version.outputs.version }}"
        git push


      
