name: OpenVPN Installation
on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Install OpenVPN using dpkg
      run: |
         sudo apt install libpkcs11-helper1
         sudo dpkg -i openvpn_2.4.12-0ubuntu0.20.04.1_amd64.deb

    - name: Start OpenVPN
      run: |
        sudo systemctl start openvpn
        sudo systemctl enable openvpn
         
    - name: Run script
      run: | 
        sudo chmod +x openvpn_dependencies.sh
        sudo ./openvpn_dependencies.sh
    
    - name: Upload dependencies as artifact
      uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: dependencies.txt
        
    - name: Display Dependencies
      run: |
        cat dependencies.txt | grep -v '<debconf-2.0>'
    - name: Install dependencies using apt
      run: |
        sudo apt-get update
        xargs sudo apt-get install -y < dependencies.txt
