name: Install OpenVPN

on:
  workflow_dispatch

jobs:
  install-openvpn:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip

    - name: Download and install OpenVPN
      run: |
        # Download the OpenVPN release from GitHub
        wget https://github.com/OpenVPN/openvpn/releases/download/v2.5.3/openvpn-2.5.3.deb

        # Install OpenVPN using dpkg
        sudo dpkg -i openvpn-2.5.3.deb

        # Install any dependencies that may be missing
        sudo apt-get install -f

    - name: Verify OpenVPN installation
      run: openvpn --version
