name: OpenVPN Installation
on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install My Application
      run: |
        #sudo apt-get install libpkcs11-helper1
        #sudo apt-get install libjsoncpp25
        #sudo apt-get install libprotobuf23

        #sudo dpkg -i openvpn_2.4.12-0ubuntu0.20.04.1_amd64.deb
        sudo dpkg -i openvpn_2.5.9-0ubuntu0.22.04.2_amd64.deb

    - name: Start OpenVPN
      run: |
        sudo systemctl start openvpn
        sudo systemctl enable openvpn
        

