name: OpenVPN Installation
on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install My Application
      run: |
        sudo apt install apt-transport-https
        sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
        sudo apt-key add openvpn-repo-pkg-key.pub
        sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-jammy.list
        sudo apt update
        sudo apt install openvpn3
     

    - name: Run script
      run: | 
        sudo chmod +x openvpn_dependencies.sh
        sudo ./openvpn_dependencies.sh > dependencies.txt

    - name: Upload dependencies as artifact
      uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: dependencies.txt
        
    - name: Display Dependencies
      run: |
        cat dependencies.txt

    - name: Install Dependencies using dpkg
      run: |
        sudo xargs dpkg -i < dependencies.txt || sudo apt-get install -f
