name: Download File from S3
on:
  workflow_dispatch:

jobs:
  download_file:
    runs-on: ubuntu-latest

    outputs:
      # Define the output variable new_version
      id: download_file_output
      value: ${{ steps.download_file.outputs.new_version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download file from S3
      run: |
        aws s3 cp s3://ver-bucket-test/version.txt .
        current_version=$(cat version.txt)
        new_version=$(echo $current_version | awk -F'.' '{print $1"."$2"."$3+1}')
        echo "file version = $new_version" > test.txt
        echo $new_version > new_version.txt

    - name: Show updated version
      run: cat version.txt

    #- name: Update version in app.ts
     # run: |
      #   sed -i "s/'com.revvity.streamrelay': {\s*version: '[0-9.]*'/\'com.revvity.streamrelay': {\n            version: '$new_version'/" app.ts
        
    - name: Commit and Push Changes
      run: |
        git config --local user.email "sijinthomaspalliyady@gmail.com"
        git config --local user.name "Sijin Thomas"
        git add test.txt app.ts
        git commit -m "Bump version to ${{ needs.download_file.outputs.new_version }}"
        git push

    - name: Display the new version
      run: |
        new_version=$(cat new_version.txt)
        echo "New version: $new_version"
        #sed -i "s/'com.revvity.streamrelay': {\s*version: '[0-9.]*'/\'com.revvity.streamrelay': {\n            version: '$new_version'/" app.ts
        awk -v new_version="$new_version" '/'\''com\.revvity\.streamrelay'\''/ {gsub(/version: '\''[0-9.]+'\''/, "version: '\''" new_version "'\''")}1' app.ts > app.ts.tmp && mv app.ts.tmp app.ts
