name: Install OpenVPN

on:
  workflow_dispatch

jobs:
  install-openvpn:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip

    - name: Download and install OpenVPN
      run: |
        sudo apt install libpkcs11-helper1
        # Download the OpenVPN release from GitHub
        wget https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/openvpn_2.5.5-1ubuntu3_amd64.deb.html

        # Install OpenVPN using dpkg
        sudo dpkg -i openvpn_2.5.5-1ubuntu3_amd64.deb

        # Install any dependencies that may be missing
        sudo apt-get install -f

    - name: Verify OpenVPN installation
      run: openvpn --version
