name: OpenVPN Installation
on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install My Application
      run: |
        sudo apt install libpkcs11-helper1
        sudo apt-cache depends openvpn
        sudo dpkg -i openvpn_2.4.12-0ubuntu0.20.04.1_amd64.deb
        sudo apt-get install -f  # Install dependencies
        sudo apt-get check
   
