name: OpenVPN Installation
on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install My Application
      run: |
        sudo apt install apt-transport-https
        sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
        sudo apt-key add openvpn-repo-pkg-key.pub
        sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-jammy.list
        sudo apt update
        sudo apt install openvpn3 > installation_log.txt 2>&1
        cat installation_log.txt
       
    - name: Run script
      run: | 
        sudo chmod +x openvpn_dependencies.sh
        sudo ./openvpn_dependencies.sh

    - name: Extract line 91 from log file
      run: |
        LINE_91=$(sed -n '91p' installation_log.txt)
        echo "Line 91: $LINE_91"
        echo "$LINE_91" > line_91.txt
        cat line_91.txt

    - name: Use dpkg to install files
      run: |
        sudo dpkg -i $(cat line_91.txt)
