name: OpenVPN Installation
on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install My Application
      run: |
        sudo apt-get install libpkcs11-helper1
        sudo apt-get install libjsoncpp25
        sudo apt-get install libprotobuf23

        sudo dpkg -i openvpn_2.4.12-0ubuntu0.20.04.1_amd64.deb
        
     
    - name: Run script
      run: | 
        sudo chmod +x openvpn_dependencies.sh
        sudo ./openvpn_dependencies.sh > dependencies.txt

    - name: Upload dependencies as artifact
      uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: dependencies.txt

    - name: Extract new packages
      run: |
        sed -n '/The following NEW packages will be installed:/,/^0 upgraded,/{/^0 upgraded,/!p}' dependencies.txt > new_packages.txt

    - name: Display New Packages
      run: |
        cat new_packages.txt

