name: OpenVPN Installation
on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install My Application
      run: |
        # Replace 'your-package-name.deb' with the actual name of your .deb file
        # sudo apt install libpkcs11-helper1
        sudo dpkg -I openvpn_2.4.12-0ubuntu0.20.04.1_amd64.deb
        sudo apt-get install -f  # Install dependencies
        sudo apt-get check
    - name: Verify OpenVPN Installation
      run: |
        if ! command -v openvpn &> /dev/null
        then
        echo "OpenVPN is not installed"
        exit 1
        fi
        openvpn --version
        sudo systemctl status openvpn
        ifconfig
        shell: /usr/bin/bash -e {0}
